services:
  postgres:
    image: docker.io/postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  backend:
    build :
      context : src/
      dockerfile: ../docker_files/Dockerfile.backend
    env_file : 
      - .env

    depends_on :
    - postgres

  frontend :
    build:
      context: src/frontend
      dockerfile: ../../docker_files/Dockerfile.frontend
    ports :
     - 8080:80
    depends_on :
    - backend


volumes:
  postgres_data: