FROM node:20-alpine

WORKDIR /app 
#if no folder conflict with package.json inside docker# 

COPY package*.json ./
COPY prisma.config.ts ./
COPY tsconfig*.json ./
COPY backend/entrypoint.sh ./
RUN npm install

COPY . .

RUN npx prisma generate --schema=backend/prisma/schema.prisma --config=prisma.config.ts

RUN npx tsc -b tsconfig.json

EXPOSE 3000

CMD ["sh", "./entrypoint.sh"]