FROM node:20-alpine

WORKDIR /app 
#if no folder conflict with package.json inside docker# 

COPY package*.json ./
COPY prisma.config.ts ./
COPY tsconfig*.json ./
RUN npm install

COPY . .

RUN npx prisma generate --schema=backend/prisma/schema.prisma --config=prisma.config.ts

RUN npx tsc -b tsconfig.json

EXPOSE 3000

CMD ["sh", "-c", "npx prisma db push --schema=backend/prisma/schema.prisma && node build/backend/server.js"]