FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

RUN apk add --no-cache openssl

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY nginx/entrypoint.sh /usr/local/bin/generate-ssl.sh

RUN chmod +x /usr/local/bin/generate-ssl.sh

ENTRYPOINT ["/usr/local/bin/generate-ssl.sh"]

STOPSIGNAL SIGQUIT

EXPOSE 80 443